import { NextRequest, NextResponse } from "next/server";
import {
  generateWithLLM,
  LLMRefusedError,
  LLMUpstreamError,
} from "@/lib/web3-promo-image-factory/llm";
import {
  checkEntitlement,
  consumeEntitlement,
} from "@/lib/entitlement";
import type {
  GenerateRequest,
  GenerateResponse,
  ProjectType,
  VisualGoal,
  VisualStyle,
  ToneType,
  OutputMode,
} from "@/lib/web3-promo-image-factory/types";

const PRODUCT_SLUG = "web3-promo-image-factory";
const DISCLAIMER =
  "Image prompts generated by AI. Review and customize before publishing. For best results, use with Midjourney, DALL-E, Leonardo, or Ideogram.";

const VALID_PROJECT_TYPES: ProjectType[] = [
  "Meme Coin",
  "NFT Project",
  "AI Agent",
  "Telegram Bot",
  "DeFi Tool",
  "Web3 Tool",
  "Crypto Community",
];

const VALID_VISUAL_GOALS: VisualGoal[] = [
  "Launch Poster",
  "Meme Image",
  "X Promo Image",
  "Telegram Announcement Image",
  "Community Engagement Image",
  "Partnership Visual",
  "Airdrop Campaign Visual",
];

const VALID_STYLES: VisualStyle[] = [
  "Cyberpunk",
  "Clean Web3",
  "Meme / Degen",
  "Futuristic",
  "Premium Fintech",
  "Dark Crypto",
  "Cute Mascot",
];

const VALID_TONES: ToneType[] = [
  "Serious",
  "Funny",
  "Degen",
  "Professional",
  "Community-first",
];

const VALID_OUTPUT_MODES: OutputMode[] = [
  "Prompt Only",
  "Visual Brief",
  "Image if provider available",
];

function validateInput(body: unknown): GenerateRequest | { error: string } {
  if (!body || typeof body !== "object") {
    return { error: "Request body must be a JSON object" };
  }
  const o = body as Record<string, unknown>;

  const projectName = String(o.projectName ?? "").trim();
  if (!projectName || projectName.length > 120) {
    return { error: "projectName must be 1-120 characters" };
  }

  const projectTypeRaw = String(o.projectType ?? "").trim();
  if (!VALID_PROJECT_TYPES.includes(projectTypeRaw as ProjectType)) {
    return { error: `Invalid projectType. Options: ${VALID_PROJECT_TYPES.join(", ")}` };
  }

  const projectDescription = String(o.projectDescription ?? "").trim();
  if (projectDescription.length < 10 || projectDescription.length > 2000) {
    return { error: "projectDescription must be 10-2000 characters" };
  }

  const visualGoalRaw = String(o.visualGoal ?? "").trim();
  if (!VALID_VISUAL_GOALS.includes(visualGoalRaw as VisualGoal)) {
    return { error: `Invalid visualGoal. Options: ${VALID_VISUAL_GOALS.join(", ")}` };
  }

  const styleRaw = String(o.style ?? "").trim();
  if (!VALID_STYLES.includes(styleRaw as VisualStyle)) {
    return { error: `Invalid style. Options: ${VALID_STYLES.join(", ")}` };
  }

  const toneRaw = String(o.tone ?? "").trim();
  if (!VALID_TONES.includes(toneRaw as ToneType)) {
    return { error: `Invalid tone. Options: ${VALID_TONES.join(", ")}` };
  }

  const keyMessage = String(o.keyMessage ?? "").trim();
  if (keyMessage.length > 500) {
    return { error: "keyMessage must be ≤ 500 characters" };
  }

  const brandColors = o.brandColors != null ? String(o.brandColors).trim() : "";
  const logoDescription = o.logoDescription != null ? String(o.logoDescription).trim() : "";

  const outputModeRaw = String(o.outputMode ?? "Prompt Only").trim();
  const outputMode = VALID_OUTPUT_MODES.includes(outputModeRaw as OutputMode)
    ? (outputModeRaw as OutputMode)
    : "Prompt Only";

  return {
    projectName,
    projectType: projectTypeRaw as ProjectType,
    projectDescription,
    visualGoal: visualGoalRaw as VisualGoal,
    style: styleRaw as VisualStyle,
    tone: toneRaw as ToneType,
    keyMessage,
    brandColors,
    logoDescription,
    outputMode,
  };
}

export async function POST(request: NextRequest) {
  try {
    const ent = await checkEntitlement(request, PRODUCT_SLUG);
    if (!ent.ok) {
      return NextResponse.json(
        {
          error: ent.errorCode,
          message: ent.error,
        },
        { status: ent.status },
      );
    }

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: "INVALID_INPUT", message: "Request body is not valid JSON" },
        { status: 400 },
      );
    }

    const v = validateInput(body);
    if ("error" in v) {
      return NextResponse.json(
        { error: "INVALID_INPUT", message: v.error },
        { status: 400 },
      );
    }
    const req: GenerateRequest = v;

    let llmResult;
    try {
      llmResult = await generateWithLLM(req);
    } catch (err) {
      if (err instanceof LLMRefusedError) {
        return NextResponse.json(
          { error: "LLM_REFUSED", message: "Unable to generate content from the provided input" },
          { status: 422 },
        );
      }
      if (err instanceof LLMUpstreamError) {
        console.error("LLM upstream error:", err.status, err.detail);
        return NextResponse.json(
          {
            error: "LLM_UPSTREAM",
            message: "AI service temporarily unavailable, please try again later",
          },
          { status: 502 },
        );
      }
      const msg = err instanceof Error ? err.message : "unknown";
      console.error("LLM unknown error:", msg);
      return NextResponse.json(
        { error: "INTERNAL", message: "Internal server error" },
        { status: 500 },
      );
    }

    consumeEntitlement(PRODUCT_SLUG, ent).catch(() => {});

    const response: GenerateResponse = {
      request: req,
      content: llmResult.output,
      disclaimer: DISCLAIMER,
      meta: {
        licenseUsage: ent.totalQuota - ent.remainingUses + (ent.ok ? 1 : 0),
        licenseQuota: ent.totalQuota,
        promptTokens: llmResult.promptTokens,
        completionTokens: llmResult.completionTokens,
        mode: ent.mode,
      },
    };

    return NextResponse.json(response);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    console.error("API route uncaught exception:", msg);
    return NextResponse.json(
      { error: "INTERNAL", message: "Server error, please try again later" },
      { status: 500 },
    );
  }
}

export async function GET() {
  return NextResponse.json(
    { error: "METHOD_NOT_ALLOWED", message: "POST only" },
    { status: 405 },
  );
}
