// ============================================================
// Partnership Announcement Generator · API（Edge 兼容）
//
// POST /api/partnership-announcement-generator/generate
// Headers: X-License: <license_code>
// Body:    GenerateRequest
//
// 流程：
//   1. 校验 license
//   2. 校验输入字段
//   3. 单次 LLM 调用（DeepSeek，JSON Mode）
//   4. license 用量自增（best-effort）
//   5. 返回 GenerateResponse
//
// 错误码：
//   400 INVALID_INPUT
//   402 INVALID_LICENSE / LICENSE_EXHAUSTED
//   502 LLM_UPSTREAM
// ============================================================

import { NextRequest, NextResponse } from "next/server";
import {
  findLicenseUsage,
  incrementLicenseUsage,
  type LicenseUsageRecord,
} from "@/lib/firestore-client";
import {
  generateWithLLM,
  LLMRefusedError,
  LLMUpstreamError,
} from "@/lib/partnership-announcement/llm";
import type {
  GenerateRequest,
  GenerateResponse,
  PartnershipType,
  ToneType,
  LengthType,
} from "@/lib/partnership-announcement/types";

const PRODUCT_SLUG = "partnership-announcement-generator";
const DISCLAIMER =
  "Content generated by AI. Please review and customize before publishing. We are not responsible for any content publishing issues.";

const VALID_PARTNERSHIP_TYPES: PartnershipType[] = [
  "Strategic Partnership",
  "Ecosystem Partnership",
  "Technology Integration",
  "Marketing Collaboration",
  "Community Partnership",
];

const VALID_TONES: ToneType[] = [
  "Professional",
  "Exciting",
  "Community-first",
  "Investor-focused",
];

const VALID_LENGTHS: LengthType[] = ["Short", "Medium", "Long"];

// ------------------------------------------------------------
// 输入校验
// ------------------------------------------------------------

function validateInput(body: unknown): GenerateRequest | { error: string } {
  if (!body || typeof body !== "object") {
    return { error: "请求体必须是 JSON 对象" };
  }
  const o = body as Record<string, unknown>;

  const projectAName = String(o.projectAName ?? "").trim();
  if (!projectAName || projectAName.length > 120) {
    return { error: "projectAName 长度需在 1~120 字符" };
  }

  const projectBName = String(o.projectBName ?? "").trim();
  if (!projectBName || projectBName.length > 120) {
    return { error: "projectBName 长度需在 1~120 字符" };
  }

  const projectADescription = String(o.projectADescription ?? "").trim();
  const trimmedADescription = projectADescription;
  if (trimmedADescription.length < 4 || trimmedADescription.length > 2000) {
    return { error: "projectADescription 长度需在 4~2000 字符（不计前后空格）" };
  }

  const projectBDescription = String(o.projectBDescription ?? "").trim();
  const trimmedBDescription = projectBDescription;
  if (trimmedBDescription.length < 4 || trimmedBDescription.length > 2000) {
    return { error: "projectBDescription 长度需在 4~2000 字符（不计前后空格）" };
  }

  const partnershipTypeRaw = String(o.partnershipType ?? "").trim();
  if (!VALID_PARTNERSHIP_TYPES.includes(partnershipTypeRaw as PartnershipType)) {
    return {
      error: `partnershipType 需为以下之一: ${VALID_PARTNERSHIP_TYPES.join(", ")}`,
    };
  }
  const partnershipType = partnershipTypeRaw as PartnershipType;

  const mainBenefits = String(o.mainBenefits ?? "").trim();
  if (mainBenefits.length < 4 || mainBenefits.length > 2000) {
    return { error: "mainBenefits 长度需在 4~2000 字符" };
  }

  const websiteLinks = String(o.websiteLinks ?? "").trim();
  if (websiteLinks.length > 1000) {
    return { error: "websiteLinks 长度需 ≤ 1000 字符" };
  }

  const toneRaw = String(o.tone ?? "").trim();
  if (!VALID_TONES.includes(toneRaw as ToneType)) {
    return {
      error: `tone 需为以下之一: ${VALID_TONES.join(", ")}`,
    };
  }
  const tone = toneRaw as ToneType;

  const lengthRaw = String(o.length ?? "").trim();
  if (!VALID_LENGTHS.includes(lengthRaw as LengthType)) {
    return {
      error: `length 需为以下之一: ${VALID_LENGTHS.join(", ")}`,
    };
  }
  const length = lengthRaw as LengthType;

  return {
    projectAName,
    projectBName,
    projectADescription,
    projectBDescription,
    partnershipType,
    mainBenefits,
    websiteLinks,
    tone,
    length,
  };
}

// ------------------------------------------------------------
// License 校验
// ------------------------------------------------------------

interface LicenseCheckOk {
  ok: true;
  bypass?: boolean;
  record?: LicenseUsageRecord;
}
interface LicenseCheckFail {
  ok: false;
  status: number;
  error: string;
}

async function checkLicense(
  request: NextRequest,
): Promise<LicenseCheckOk | LicenseCheckFail> {
  const license = (request.headers.get("x-license") ?? "").trim();

  if (process.env.PARTNERSHIP_ANNOUNCEMENT_LICENSE_BYPASS === "1") {
    return { ok: true, bypass: true };
  }

  if (!license || license.length < 8) {
    return { ok: false, status: 402, error: "缺少或无效的 X-License 授权码" };
  }

  let record: LicenseUsageRecord | null;
  try {
    record = await findLicenseUsage(license);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    console.error("findLicenseUsage 失败:", msg);
    return { ok: false, status: 502, error: "授权码校验服务暂不可用" };
  }

  if (!record) {
    return { ok: false, status: 402, error: "授权码不存在或已失效" };
  }

  if (record.productSlug !== PRODUCT_SLUG) {
    return {
      ok: false,
      status: 402,
      error: `此授权码不适用于本工具（属于 ${record.productSlug}）`,
    };
  }

  if (record.usedCount >= record.quota) {
    return {
      ok: false,
      status: 402,
      error: `授权码用量已达上限（${record.quota} 次）`,
    };
  }

  return { ok: true, record };
}

// ------------------------------------------------------------
// POST handler
// ------------------------------------------------------------

export async function POST(request: NextRequest) {
  const lic = await checkLicense(request);
  if (!lic.ok) {
    return NextResponse.json(
      { error: lic.status === 402 ? "INVALID_LICENSE" : "UPSTREAM", message: lic.error },
      { status: lic.status },
    );
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "INVALID_INPUT", message: "请求体不是合法的 JSON" },
      { status: 400 },
    );
  }
  const v = validateInput(body);
  if ("error" in v) {
    return NextResponse.json(
      { error: "INVALID_INPUT", message: v.error },
      { status: 400 },
    );
  }
  const req: GenerateRequest = v;

  let llmResult;
  try {
    llmResult = await generateWithLLM(req);
  } catch (err) {
    if (err instanceof LLMRefusedError) {
      return NextResponse.json(
        { error: "LLM_REFUSED", message: "输入信息不足，无法生成公告" },
        { status: 422 },
      );
    }
    if (err instanceof LLMUpstreamError) {
      console.error("LLM 上游错误:", err.status, err.detail);
      return NextResponse.json(
        { error: "LLM_UPSTREAM", message: "AI 推理服务暂时不可用，请稍后再试" },
        { status: 502 },
      );
    }
    const msg = err instanceof Error ? err.message : "unknown";
    console.error("LLM 未知错误:", msg);
    return NextResponse.json(
      { error: "INTERNAL", message: "服务器内部错误" },
      { status: 500 },
    );
  }

  let licenseUsage = 0;
  let licenseQuota = 0;
  if (lic.bypass) {
    licenseUsage = 0;
    licenseQuota = 9999;
  } else if (lic.record) {
    licenseUsage = lic.record.usedCount + 1;
    licenseQuota = lic.record.quota;
    incrementLicenseUsage(lic.record.license, lic.record).catch((err) => {
      const m = err instanceof Error ? err.message : "unknown";
      console.warn("incrementLicenseUsage 失败 (非致命):", m);
    });
  }

  const response: GenerateResponse = {
    request: req,
    content: llmResult.output,
    disclaimer: DISCLAIMER,
    meta: {
      licenseUsage,
      licenseQuota,
      promptTokens: llmResult.promptTokens,
      completionTokens: llmResult.completionTokens,
    },
  };

  return NextResponse.json(response);
}

export async function GET() {
  return NextResponse.json(
    { error: "METHOD_NOT_ALLOWED", message: "仅支持 POST" },
    { status: 405 },
  );
}
