// ============================================================
// Partnership Announcement Generator · API（Edge 兼容）
//
// POST /api/partnership-announcement-generator/generate
// Headers: X-License: <license_code>
// Body:    GenerateRequest
//
// 流程：
//   1. 校验 license
//   2. 校验输入字段
//   3. 单次 LLM 调用（DeepSeek，JSON Mode）
//   4. license 用量自增（best-effort）
//   5. 返回 GenerateResponse
//
// 错误码：
//   400 INVALID_INPUT
//   402 INVALID_LICENSE / LICENSE_EXHAUSTED
//   502 LLM_UPSTREAM
// ============================================================

import { NextRequest, NextResponse } from "next/server";
import {
  generateWithLLM,
  LLMRefusedError,
  LLMUpstreamError,
} from "@/lib/partnership-announcement/llm";
import {
  checkEntitlement,
  consumeEntitlement,
} from "@/lib/entitlement";
import type {
  GenerateRequest,
  GenerateResponse,
  PartnershipType,
  ToneType,
  LengthType,
} from "@/lib/partnership-announcement/types";

const PRODUCT_SLUG = "partnership-announcement-generator";
const DISCLAIMER =
  "Content generated by AI. Please review and customize before publishing.";

const VALID_PARTNERSHIP_TYPES: PartnershipType[] = [
  "Strategic Partnership",
  "Ecosystem Partnership",
  "Technology Integration",
  "Marketing Collaboration",
  "Community Partnership",
];

const VALID_TONES: ToneType[] = [
  "Professional",
  "Exciting",
  "Community-first",
  "Investor-focused",
];

const VALID_LENGTHS: LengthType[] = ["Short", "Medium", "Long"];

// ------------------------------------------------------------
// 输入校验
// ------------------------------------------------------------

function validateInput(body: unknown): GenerateRequest | { error: string } {
  if (!body || typeof body !== "object") {
    return { error: "请求体必须是 JSON 对象" };
  }
  const o = body as Record<string, unknown>;

  const projectAName = String(o.projectAName ?? "").trim();
  if (!projectAName || projectAName.length > 120) {
    return { error: "projectAName 长度需在 1~120 字符" };
  }

  const projectBName = String(o.projectBName ?? "").trim();
  if (!projectBName || projectBName.length > 120) {
    return { error: "projectBName 长度需在 1~120 字符" };
  }

  const projectADescription = String(o.projectADescription ?? "").trim();
  const trimmedADescription = projectADescription;
  if (trimmedADescription.length < 4 || trimmedADescription.length > 2000) {
    return {
      error: "projectADescription 长度需在 4~2000 字符（不计前后空格）",
    };
  }

  const projectBDescription = String(o.projectBDescription ?? "").trim();
  const trimmedBDescription = projectBDescription;
  if (trimmedBDescription.length < 4 || trimmedBDescription.length > 2000) {
    return {
      error: "projectBDescription 长度需在 4~2000 字符（不计前后空格）",
    };
  }

  const partnershipTypeRaw = String(o.partnershipType ?? "").trim();
  if (
    !VALID_PARTNERSHIP_TYPES.includes(partnershipTypeRaw as PartnershipType)
  ) {
    return {
      error: `partnershipType 需为以下之一: ${VALID_PARTNERSHIP_TYPES.join(", ")}`,
    };
  }
  const partnershipType = partnershipTypeRaw as PartnershipType;

  const mainBenefits = String(o.mainBenefits ?? "").trim();
  if (mainBenefits.length < 4 || mainBenefits.length > 2000) {
    return { error: "mainBenefits 长度需在 4~2000 字符" };
  }

  const websiteLinks = String(o.websiteLinks ?? "").trim();
  if (websiteLinks.length > 1000) {
    return { error: "websiteLinks 长度需 ≤ 1000 字符" };
  }

  const toneRaw = String(o.tone ?? "").trim();
  if (!VALID_TONES.includes(toneRaw as ToneType)) {
    return {
      error: `tone 需为以下之一: ${VALID_TONES.join(", ")}`,
    };
  }
  const tone = toneRaw as ToneType;

  const lengthRaw = String(o.length ?? "").trim();
  if (!VALID_LENGTHS.includes(lengthRaw as LengthType)) {
    return {
      error: `length 需为以下之一: ${VALID_LENGTHS.join(", ")}`,
    };
  }
  const length = lengthRaw as LengthType;

  return {
    projectAName,
    projectBName,
    projectADescription,
    projectBDescription,
    partnershipType,
    mainBenefits,
    websiteLinks,
    tone,
    length,
  };
}

// ------------------------------------------------------------
// POST handler
// ------------------------------------------------------------

export async function POST(request: NextRequest) {
  try {
    const ent = await checkEntitlement(request, PRODUCT_SLUG);
    if (!ent.ok) {
      return NextResponse.json(
        {
          error: ent.errorCode,
          message: ent.error,
        },
        { status: ent.status },
      );
    }

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: "INVALID_INPUT", message: "Request body is not valid JSON" },
        { status: 400 },
      );
    }
    const v = validateInput(body);
    if ("error" in v) {
      return NextResponse.json(
        { error: "INVALID_INPUT", message: v.error },
        { status: 400 },
      );
    }
    const req: GenerateRequest = v;

    let llmResult;
    try {
      llmResult = await generateWithLLM(req);
    } catch (err) {
      if (err instanceof LLMRefusedError) {
        return NextResponse.json(
          { error: "LLM_REFUSED", message: "Insufficient information to generate announcement" },
          { status: 422 },
        );
      }
      if (err instanceof LLMUpstreamError) {
        console.error("LLM upstream error:", err.status, err.detail);
        return NextResponse.json(
          {
            error: "LLM_UPSTREAM",
            message: "AI service temporarily unavailable, please try again later",
          },
          { status: 502 },
        );
      }
      const msg = err instanceof Error ? err.message : "unknown";
      console.error("LLM unknown error:", msg);
      return NextResponse.json(
        { error: "INTERNAL", message: "Internal server error" },
        { status: 500 },
      );
    }

    consumeEntitlement(PRODUCT_SLUG, ent).catch(() => {});

    const response: GenerateResponse = {
      request: req,
      content: llmResult.output,
      disclaimer: DISCLAIMER,
      meta: {
        licenseUsage: ent.totalQuota - ent.remainingUses + (ent.ok ? 1 : 0),
        licenseQuota: ent.totalQuota,
        promptTokens: llmResult.promptTokens,
        completionTokens: llmResult.completionTokens,
        mode: ent.mode,
      },
    };

    return NextResponse.json(response);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    console.error("API route uncaught exception:", msg);
    return NextResponse.json(
      { error: "INTERNAL", message: "Server error, please try again later" },
      { status: 500 },
    );
  }
}

export async function GET() {
  return NextResponse.json(
    { error: "METHOD_NOT_ALLOWED", message: "仅支持 POST" },
    { status: 405 },
  );
}
