import { NextRequest, NextResponse } from "next/server";
import {
  generateWithLLM,
  LLMRefusedError,
  LLMUpstreamError,
} from "@/lib/web3-content-factory/llm";
import {
  checkEntitlement,
  consumeEntitlement,
} from "@/lib/entitlement";
import type {
  GenerateRequest,
  GenerateResponse,
  ProjectType,
  ProjectStage,
  ToneType,
} from "@/lib/web3-content-factory/types";

const PRODUCT_SLUG = "web3-content-factory";
const DISCLAIMER =
  "Content generated by AI. Review and customize before publishing.";

const VALID_PROJECT_TYPES: ProjectType[] = [
  "Meme Coin",
  "NFT Project",
  "AI Agent",
  "Telegram Bot",
  "DeFi Tool",
  "Web3 Tool",
];

const VALID_STAGES: ProjectStage[] = [
  "Pre-launch",
  "Launched",
  "Presale",
  "Airdrop",
  "Community Growth",
];

const VALID_TONES: ToneType[] = [
  "Degen",
  "Professional",
  "Funny",
  "Community-first",
  "Investor-focused",
];

function validateInput(body: unknown): GenerateRequest | { error: string } {
  if (!body || typeof body !== "object") {
    return { error: "Request body must be a JSON object" };
  }
  const o = body as Record<string, unknown>;

  const projectName = String(o.projectName ?? "").trim();
  if (!projectName || projectName.length > 120) {
    return { error: "projectName must be 1-120 characters" };
  }

  const projectTypeRaw = String(o.projectType ?? "").trim();
  if (!VALID_PROJECT_TYPES.includes(projectTypeRaw as ProjectType)) {
    return { error: `Invalid projectType. Options: ${VALID_PROJECT_TYPES.join(", ")}` };
  }
  const projectType = projectTypeRaw as ProjectType;

  const projectDescription = String(o.projectDescription ?? "").trim();
  if (projectDescription.length < 10 || projectDescription.length > 2000) {
    return { error: "projectDescription must be 10-2000 characters" };
  }

  const targetAudience = String(o.targetAudience ?? "").trim();
  if (targetAudience.length > 1000) {
    return { error: "targetAudience must be ≤ 1000 characters" };
  }

  const stageRaw = String(o.stage ?? "").trim();
  if (!VALID_STAGES.includes(stageRaw as ProjectStage)) {
    return { error: `Invalid stage. Options: ${VALID_STAGES.join(", ")}` };
  }
  const stage = stageRaw as ProjectStage;

  const toneRaw = String(o.tone ?? "").trim();
  if (!VALID_TONES.includes(toneRaw as ToneType)) {
    return { error: `Invalid tone. Options: ${VALID_TONES.join(", ")}` };
  }
  const tone = toneRaw as ToneType;

  const websiteLinks = String(o.websiteLinks ?? "").trim();
  if (websiteLinks.length > 1000) {
    return { error: "websiteLinks must be ≤ 1000 characters" };
  }

  return {
    projectName,
    projectType,
    projectDescription,
    targetAudience,
    stage,
    tone,
    websiteLinks,
  };
}

export async function POST(request: NextRequest) {
  try {
    const ent = await checkEntitlement(request, PRODUCT_SLUG);
    if (!ent.ok) {
      return NextResponse.json(
        {
          error: ent.errorCode,
          message: ent.error,
        },
        { status: ent.status },
      );
    }

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: "INVALID_INPUT", message: "Request body is not valid JSON" },
        { status: 400 },
      );
    }

    const v = validateInput(body);
    if ("error" in v) {
      return NextResponse.json(
        { error: "INVALID_INPUT", message: v.error },
        { status: 400 },
      );
    }
    const req: GenerateRequest = v;

    let llmResult;
    try {
      llmResult = await generateWithLLM(req);
    } catch (err) {
      if (err instanceof LLMRefusedError) {
        return NextResponse.json(
          { error: "LLM_REFUSED", message: "Unable to generate content from the provided input" },
          { status: 422 },
        );
      }
      if (err instanceof LLMUpstreamError) {
        console.error("LLM upstream error:", err.status, err.detail);
        return NextResponse.json(
          {
            error: "LLM_UPSTREAM",
            message: "AI service temporarily unavailable, please try again later",
          },
          { status: 502 },
        );
      }
      const msg = err instanceof Error ? err.message : "unknown";
      console.error("LLM unknown error:", msg);
      return NextResponse.json(
        { error: "INTERNAL", message: "Internal server error" },
        { status: 500 },
      );
    }

    consumeEntitlement(PRODUCT_SLUG, ent).catch(() => {});

    const response: GenerateResponse = {
      request: req,
      content: llmResult.output,
      disclaimer: DISCLAIMER,
      meta: {
        licenseUsage: ent.totalQuota - ent.remainingUses + (ent.ok ? 1 : 0),
        licenseQuota: ent.totalQuota,
        promptTokens: llmResult.promptTokens,
        completionTokens: llmResult.completionTokens,
        mode: ent.mode,
      },
    };

    return NextResponse.json(response);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "unknown";
    console.error("API route uncaught exception:", msg);
    return NextResponse.json(
      { error: "INTERNAL", message: "Server error, please try again later" },
      { status: 500 },
    );
  }
}

export async function GET() {
  return NextResponse.json(
    { error: "METHOD_NOT_ALLOWED", message: "POST only" },
    { status: 405 },
  );
}
